### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using litellm https://github.com/BerriAI/litellm

TLDR: langstream gets:
- more models out of the box, everything litellm integrates with: https://litellm.readthedocs.io/en/latest/supported/ 
- instant integration of new models by modifying the `model` param (Easy to add models in the future, just change the model param)

Here's a sample of how it's used:
```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
addressing https://github.com/rogeriochaves/langstream/issues/5

**Comment by ishaan-jaff** [comment]
@rogeriochaves can you please take a look at this PR ? If this initial commit looks good happy to add more docs/tests too😊

**Comment by rogeriochaves** [comment]
hey! Sorry for the delay, gotta fix my notifications. Great work! Thanks for the contribution, will test it more carefully and merge in a bit. Would you mind writing docs for it as well?

**Comment by rogeriochaves** [comment]
I got an error when running the integration tests:

```
TypeError: completion() got an unexpected keyword argument 'timeout'
```

seems like the API is not 100% compatible with OpenAI, and thinking about that, I don't want to merge this under OpenAI, specially because the API can diverge anytime, however I like the idea of having LiteLLM being supported

could you instead of replacing the OpenAI call, simply copy and pasting and having another module for LiteLLM? I don't mind the code duplication, but I mind users not being able to trust that using the OpenAI module really uses the official OpenAI under the hood with no further wrappers. However, with the right words in documentation we can point users that this is a great way to use Azure, OpenAI, Palm, Anthropic, Cohere, Replicate Models etc all at the same time, and I really like this concept

**Comment by rogeriochaves** [comment]
@ishaan-jaff I've implemented it in #10, take a look at what you think, and please add improvements if you can think of. Closing this one

**Pull request closed without merging**
